# Generated by Django 4.2.17 on 2025-01-04 12:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('education_courses', '0004_course_section_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
